# Server port
server.port=${PORT:8080}

# Render PostgreSQL
spring.datasource.url=jdbc:postgresql://dpg-d6k2j9fkijhs73ffe2j0-a.oregon-postgres.render.com:5432/quizapp_4hv4?sslmode=require
spring.datasource.username=quizapp_4hv4_user
spring.datasource.password=pmAkQaLQ54H3RtAF4jZwULJbhUFms7hD
spring.datasource.driver-class-name=org.postgresql.Driver

# HikariCP
spring.datasource.hikari.keepalive-time=300000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.connection-timeout=30000

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect