spring.application.name=Quizapp

# Database Configuration (Render PostgreSQL)
spring.datasource.url=jdbc:postgresql://containers-us-west-123.railway.app:5432/quizapp
spring.datasource.username=rahul
spring.datasource.password=mypassword

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Server port
server.port=8081